"""Schematic catalog for divine construction.

Loads the catalog index generated by the data pipeline and provides
browse/inspect/build functionality for the LLM gods.
"""

import json
import logging
from pathlib import Path

logger = logging.getLogger("minecraft-god")

_catalog: dict | None = None
_catalog_path = Path(__file__).parent.parent / "scripts" / "schematics" / "schematics" / "catalog.json"


def _load_catalog():
    """Load the schematic catalog from disk (lazy, cached)."""
    global _catalog
    if _catalog is not None:
        return _catalog
    if not _catalog_path.exists():
        logger.warning(f"Schematic catalog not found: {_catalog_path}")
        _catalog = {"categories": {}}
        return _catalog
    with open(_catalog_path) as f:
        _catalog = json.load(f)
    total = sum(c.get("count", len(c.get("blueprints", []))) for c in _catalog["categories"].values())
    logger.info(f"Schematic catalog loaded: {total} blueprints across {len(_catalog['categories'])} categories")
    return _catalog


def browse_schematics(category: str) -> str:
    """Browse the schematic catalog. Returns formatted text for the LLM.

    If category is "all" or empty, returns category list with counts.
    Otherwise, returns blueprints in that category.
    """
    catalog = _load_catalog()

    if not category or category == "all":
        # Return category overview
        lines = ["Available schematic categories:"]
        for cat_name in sorted(catalog["categories"]):
            cat_data = catalog["categories"][cat_name]
            count = cat_data.get("count", len(cat_data.get("blueprints", [])))
            lines.append(f"  {cat_name}: {count} blueprints")
        lines.append("\nUse browse_schematics with a specific category to see available blueprints.")
        return "\n".join(lines)

    # Find the category
    if category not in catalog["categories"]:
        # Try partial match
        matches = [c for c in catalog["categories"] if category in c]
        if len(matches) == 1:
            category = matches[0]
        elif matches:
            return f"Multiple categories match '{category}': {', '.join(matches)}. Be more specific."
        else:
            available = ", ".join(sorted(catalog["categories"]))
            return f"Category '{category}' not found. Available: {available}"

    cat_data = catalog["categories"][category]
    blueprints = cat_data.get("blueprints", [])
    lines = [f"Category '{category}' — {len(blueprints)} blueprints:\n"]
    for bp in blueprints:
        d = bp["dimensions"]
        lines.append(f"  {bp['id']}: {bp['name']} ({d['w']}x{d['h']}x{d['d']}, {bp['block_count']} blocks)")
    lines.append(f"\nUse inspect_schematic with a blueprint ID to see details, or build_schematic to construct one.")
    return "\n".join(lines)


def inspect_schematic(blueprint_id: str) -> str:
    """Get details about a specific schematic. Returns formatted text for the LLM."""
    catalog = _load_catalog()

    for cat_data in catalog["categories"].values():
        for bp in cat_data.get("blueprints", []):
            if bp["id"] == blueprint_id:
                d = bp["dimensions"]
                lines = [
                    f"Blueprint: {bp['name']}",
                    f"ID: {bp['id']}",
                    f"Dimensions: {d['w']}W x {d['h']}H x {d['d']}D",
                    f"Block count: {bp['block_count']}",
                    f"Tags: {', '.join(bp.get('tags', []))}",
                    f"Author: {bp.get('author', 'Unknown')}",
                    f"Skill level: {bp.get('skill_level', 0)}",
                    "",
                    "Use build_schematic to construct this at a location.",
                    "The structure will appear progressively from the ground up.",
                ]
                return "\n".join(lines)

    return f"Blueprint '{blueprint_id}' not found. Use browse_schematics to see available blueprints."


def build_schematic_command(blueprint_id: str, x: int, y: int, z: int, rotation: int = 0) -> dict | None:
    """Create the special schematic build command for the plugin.

    Returns a command dict with type "build_schematic" that the plugin handles specially.
    """
    catalog = _load_catalog()

    # Validate blueprint exists
    found = False
    for cat_data in catalog["categories"].values():
        for bp in cat_data.get("blueprints", []):
            if bp["id"] == blueprint_id:
                found = True
                break
        if found:
            break

    if not found:
        logger.warning(f"Blueprint not found: {blueprint_id}")
        return None

    # Validate coordinates
    for coord in (x, y, z):
        if not isinstance(coord, int) or abs(coord) > 30000:
            logger.warning(f"Invalid coordinate for schematic build: {coord}")
            return None

    # Validate rotation
    if rotation not in (0, 90, 180, 270):
        rotation = 0

    return {
        "type": "build_schematic",
        "blueprint_id": blueprint_id,
        "x": x,
        "y": y,
        "z": z,
        "rotation": rotation,
    }
